# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'autoLayout_Test02' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for autoLayout_Test02
	pod 'Charts'
	pod 'FSCalendar'
end
